### ISSUE TITLE
RCode range is not updated

### ISSUE THREAD

**Issue by HoseynHeydari** [ortclib/udns#1]
According to [rfc 2930](https://tools.ietf.org/html/rfc2930) three values added to supported "Return Code" for DNS protocol. But there is no change in the corresponding enum at the code.

**Comment by robin-raymond** [comment]
@HoseynHeydari Thanks for this -- we use this open source project in our projects but we aren't the original authors. The original project appears to be end of life stable so we just change what is required to support the project we are working on at this point. However, if you have a PR you want to propose then by all means we can look at it for inclusion into this code. Otherwise, I'm not sure we'll be able to look into this particular issue for a while. Good find though!

**Comment by robin-raymond** [comment]
@miodrag Can you investigate this issue?

**Comment by robin-raymond** [comment]
@HoseynHeydari Can you confirm this PR is what you need to resolve the issue?

**Comment by HoseynHeydari** [comment]
Thanks for your response.
Also sorry for my late response.
I was not familiar with `udns_codes.c` file enough to do what @miodrag did. Otherwise, your great team might never be annoyed.
